More testing

diff --git a/.github/workflows/docker-official.yaml b/.github/workflows/docker-official.yaml
--- a/.github/workflows/docker-official.yaml
+++ b/.github/workflows/docker-official.yaml
@@ -254,8 +254,138 @@ jobs:
   #         - { version: 26, platform: arm/v7 } # error updating yum
   #         - { version: 27, platform: s390x }
   #         - { version: 26, platform: s390x }
-  docker-amazonlinux:
-    env: {image: "amazonlinux:${{ matrix.version }}"}
+
+  # docker-amazonlinux:
+  #   env: { image: "amazonlinux:${{ matrix.version }}" }
+  #   needs: bootstrap
+  #   runs-on: ubuntu-latest
+  #   steps: *docker-steps
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       platform:
+  #         - amd64
+  #         - arm64/v8
+  #       version:
+  #         - latest
+  #         - 2
+  #         - 1
+  #       exclude:
+  #         - { version: 1, platform: arm64/v8 }
+
+  # docker-oraclelinux:
+  #   env: { image: "oraclelinux:${{ matrix.version }}" }
+  #   needs: bootstrap
+  #   runs-on: ubuntu-latest
+  #   steps: *docker-steps
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       platform:
+  #         - amd64
+  #         - arm64/v8
+  #       version:
+  #         - 8
+  #         - 7
+  #         - 6 # TODO: fix
+  #         # - 5 # update repo fails
+  #       exclude:
+  #         - { version: 6, platform: arm64/v8 }
+  #         - { version: 5, platform: arm64/v8 }
+
+  # docker-ros: # Robot operating system
+  #   env: { image: "ros:${{ matrix.version }}" }
+  #   needs: bootstrap
+  #   runs-on: ubuntu-latest
+  #   steps: *docker-steps
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       platform:
+  #         - amd64
+  #         - arm64/v8
+  #       version:
+  #         - latest
+  #         #### Rolling release
+  #         - rolling
+  #         #### ROS 2
+  #         - galactic
+  #         - foxy
+  #         #### ROS 1
+  #         - noetic
+  #         - melodic
+  #       include:
+  #         - { version: noetic, platform: arm/v7 }
+  #         - { version: melodic, platform: arm/v7 }
+
+  # # TODO: test and fix photon
+  # docker-photon: # VmWare Photon
+  #   env: { image: "photon:${{ matrix.version }}" }
+  #   needs: bootstrap
+  #   runs-on: ubuntu-latest
+  #   steps: *docker-steps
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       platform:
+  #         - amd64
+  #         - arm64/v8
+  #       version:
+  #         - latest # needs coreutils but is also missing `as`
+  #         - '4.0'
+  #         - '3.0'
+  #         - '2.0'
+  #         - '1.0'
+  #       exclude:
+  #         - { version: '2.0', platform: arm64/v8 }
+  #         - { version: '1.0', platform: arm64/v8 }
+
+  # TODO: test
+  # docker-clearlinux:
+  #   env: { image: "clearlinux:${{ matrix.version }}" }
+  #   needs: bootstrap
+  #   runs-on: ubuntu-latest
+  #   steps: *docker-steps
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       platform:
+  #         - amd64
+  #       version:
+  #         - latest # slow install
+
+  # TODO: test
+  # docker-mageia:
+  #   env: { image: "mageia:${{ matrix.version }}" }
+  #   needs: bootstrap
+  #   runs-on: ubuntu-latest
+  #   steps: *docker-steps
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       platform:
+  #         - amd64
+  #         - arm/v7
+  #         - arm64/v8
+  #       version:
+  #         - latest # slow install
+  #         - cauldron # slow install
+  #         - 8 # slow install
+  #         - 7 # slow install
+  #         - 6 # slow install
+  #         - 5 # slow install
+  #         - 4 # slow install
+  #         - 3 # slow install
+  #       exclude:
+  #         - { version: 6, platform: arm64/v8 }
+  #         - { version: 5, platform: arm/v7 }
+  #         - { version: 5, platform: arm64/v8 }
+  #         - { version: 4, platform: arm/v7 }
+  #         - { version: 4, platform: arm64/v8 }
+  #         - { version: 3, platform: arm/v7 }
+  #         - { version: 3, platform: arm64/v8 }
+  docker-rockylinux:
+    env: {image: "rockylinux:${{ matrix.version }}"}
     needs: bootstrap
     runs-on: ubuntu-latest
     steps:
@@ -319,15 +449,12 @@ jobs:
       matrix:
         platform:
           - amd64
-          - arm64/v8
+          - arm64/8
         version:
           - latest
-          - 2
-          - 1
-        exclude:
-          - {version: 1, platform: arm64/v8}
-  docker-oraclelinux:
-    env: {image: "oraclelinux:${{ matrix.version }}"}
+          - 8
+  docker-sl: # Scientific Linux
+    env: {image: "sl:${{ matrix.version }}"}
     needs: bootstrap
     runs-on: ubuntu-latest
     steps:
@@ -391,17 +518,80 @@ jobs:
       matrix:
         platform:
           - amd64
-          - arm64/v8
         version:
-          - 8
+          - latest
           - 7
           - 6
-          - 5
-        exclude:
-          - {version: 6, platform: arm64/v8}
-          - {version: 5, platform: arm64/v8}
-  docker-ros: # Robot operating system
-    env: {image: "ros:${{ matrix.version }}"}
+  docker-clefos: # For IBM Z
+    env: {image: "clefos:${{ matrix.version }}"}
+    needs: bootstrap
+    runs-on: ubuntu-latest
+    steps:
+      # Setup multi-platform support for docker
+      - uses: docker/setup-qemu-action@v1.2.0
+      # Try to create a container for the given platform and image
+      - name: Create container
+        shell: bash
+        run: |
+          set +e
+          cont=$(docker run --pull=missing --init --detach --platform linux/${{ matrix.platform }} ${{ env.image }} tail -f /dev/null)
+          set -e
+
+          echo "cont=$cont" >> $GITHUB_ENV
+          echo "cont=$cont"
+
+          if test "x$cont" = "x"; then
+            echo "::error ::Container launch failed (${{ matrix.platform }}, ${{ env.image }})."
+            exit 1
+          fi
+      # Check platforms
+      - run: uname -a
+      - if: ${{ env.cont != 0 }}
+        run: docker exec "$cont" uname -a
+      # Create the working directory
+      - if: ${{ env.cont != 0 }}
+        run: echo "workdir=/workdir" >> $GITHUB_ENV
+      - if: ${{ env.cont != 0 }}
+        run: echo "workdir=$workdir"
+      - if: ${{ env.cont != 0 }}
+        run: docker exec --user=root "$cont" mkdir "$workdir" # don't use --mode since it is not compatible
+      - if: ${{ env.cont != 0 }}
+        run: docker exec --user=root "$cont" chmod 0777 "$workdir"
+      # Copy the artifact to the working directory
+      - if: ${{ env.cont != 0 }}
+        uses: actions/download-artifact@v2
+        with: {name: bootstrap-output}
+      - if: ${{ env.cont != 0 }}
+        run: docker cp - <fileinfo.tar "$cont":"$workdir"
+      # Install dependencies
+      - if: ${{ env.cont != 0 }}
+        run: docker exec --workdir="$workdir" "$cont" bin/install-deps
+      # Build
+      - if: ${{ env.cont != 0 }}
+        run: docker exec --workdir="$workdir" "$cont" ./configure
+      - if: ${{ env.cont != 0 }}
+        run: docker exec --workdir="$workdir" "$cont" cat src/config.h
+      - if: ${{ env.cont != 0 }}
+        run: docker exec --workdir="$workdir" "$cont" cat src/fileinfo/static.h
+      - if: ${{ env.cont != 0 }}
+        run: docker exec --workdir="$workdir" "$cont" make
+      - if: ${{ env.cont != 0 }}
+        run: docker exec --workdir="$workdir" "$cont" make check
+        # # Cleanup
+        # - if: ${{ env.cont != 0 }}
+        #   run: docker stop "$cont"
+        # - if: ${{ env.cont != 0 }}
+        #   run: docker rm --force --volumes "$cont"
+    strategy:
+      fail-fast: false
+      matrix:
+        platform:
+          - s390x
+        version:
+          - latest
+          - 7
+  docker-almalinux:
+    env: {image: "almalinux:${{ matrix.version }}"}
     needs: bootstrap
     runs-on: ubuntu-latest
     steps:
@@ -468,196 +658,9 @@ jobs:
           - arm64/v8
         version:
           - latest
-          #### Rolling release
-          - rolling
-          #### ROS 2
-          - galactic
-          - foxy
-          #### ROS 1
-          - noetic
-          - melodic
-        include:
-          - {version: noetic, platform: arm/v7}
-          - {version: melodic, platform: arm/v7}
-  docker-photon: # VmWare Photon
-    env: {image: "photon:${{ matrix.version }}"}
-    needs: bootstrap
-    runs-on: ubuntu-latest
-    steps:
-      # Setup multi-platform support for docker
-      - uses: docker/setup-qemu-action@v1.2.0
-      # Try to create a container for the given platform and image
-      - name: Create container
-        shell: bash
-        run: |
-          set +e
-          cont=$(docker run --pull=missing --init --detach --platform linux/${{ matrix.platform }} ${{ env.image }} tail -f /dev/null)
-          set -e
-
-          echo "cont=$cont" >> $GITHUB_ENV
-          echo "cont=$cont"
-
-          if test "x$cont" = "x"; then
-            echo "::error ::Container launch failed (${{ matrix.platform }}, ${{ env.image }})."
-            exit 1
-          fi
-      # Check platforms
-      - run: uname -a
-      - if: ${{ env.cont != 0 }}
-        run: docker exec "$cont" uname -a
-      # Create the working directory
-      - if: ${{ env.cont != 0 }}
-        run: echo "workdir=/workdir" >> $GITHUB_ENV
-      - if: ${{ env.cont != 0 }}
-        run: echo "workdir=$workdir"
-      - if: ${{ env.cont != 0 }}
-        run: docker exec --user=root "$cont" mkdir "$workdir" # don't use --mode since it is not compatible
-      - if: ${{ env.cont != 0 }}
-        run: docker exec --user=root "$cont" chmod 0777 "$workdir"
-      # Copy the artifact to the working directory
-      - if: ${{ env.cont != 0 }}
-        uses: actions/download-artifact@v2
-        with: {name: bootstrap-output}
-      - if: ${{ env.cont != 0 }}
-        run: docker cp - <fileinfo.tar "$cont":"$workdir"
-      # Install dependencies
-      - if: ${{ env.cont != 0 }}
-        run: docker exec --workdir="$workdir" "$cont" bin/install-deps
-      # Build
-      - if: ${{ env.cont != 0 }}
-        run: docker exec --workdir="$workdir" "$cont" ./configure
-      - if: ${{ env.cont != 0 }}
-        run: docker exec --workdir="$workdir" "$cont" cat src/config.h
-      - if: ${{ env.cont != 0 }}
-        run: docker exec --workdir="$workdir" "$cont" cat src/fileinfo/static.h
-      - if: ${{ env.cont != 0 }}
-        run: docker exec --workdir="$workdir" "$cont" make
-      - if: ${{ env.cont != 0 }}
-        run: docker exec --workdir="$workdir" "$cont" make check
-        # # Cleanup
-        # - if: ${{ env.cont != 0 }}
-        #   run: docker stop "$cont"
-        # - if: ${{ env.cont != 0 }}
-        #   run: docker rm --force --volumes "$cont"
-    strategy:
-      fail-fast: false
-      matrix:
-        platform:
-          - amd64
-          - arm64/v8
-        version:
-          - latest # needs coreutils but is also missing `as`
-          - '4.0'
-          - '3.0'
-          - '2.0'
-          - '1.0'
-        exclude:
-          - {version: '2.0', platform: arm64/v8}
-          - {version: '1.0', platform: arm64/v8}
-
-# docker-clearlinux:
-#   env: { image: "clearlinux:${{ matrix.version }}" }
-#   needs: bootstrap
-#   runs-on: ubuntu-latest
-#   steps: *docker-steps
-#   strategy:
-#     fail-fast: false
-#     matrix:
-#       platform:
-#         - amd64
-#       version:
-#         - latest # slow install
-
-# docker-mageia:
-#   env: { image: "mageia:${{ matrix.version }}" }
-#   needs: bootstrap
-#   runs-on: ubuntu-latest
-#   steps: *docker-steps
-#   strategy:
-#     fail-fast: false
-#     matrix:
-#       platform:
-#         - amd64
-#         - arm/v7
-#         - arm64/v8
-#       version:
-#         - latest # slow install
-#         - cauldron # slow install
-#         - 8 # slow install
-#         - 7 # slow install
-#         - 6 # slow install
-#         - 5 # slow install
-#         - 4 # slow install
-#         - 3 # slow install
-#       exclude:
-#         - { version: 6, platform: arm64/v8 }
-#         - { version: 5, platform: arm/v7 }
-#         - { version: 5, platform: arm64/v8 }
-#         - { version: 4, platform: arm/v7 }
-#         - { version: 4, platform: arm64/v8 }
-#         - { version: 3, platform: arm/v7 }
-#         - { version: 3, platform: arm64/v8 }
-
-# docker-rockylinux:
-#   env: { image: "rockylinux:${{ matrix.version }}" }
-#   needs: bootstrap
-#   runs-on: ubuntu-latest
-#   steps: *docker-steps
-#   strategy:
-#     fail-fast: false
-#     matrix:
-#       platform:
-#         - amd64
-#         - arm64/8
-#       version:
-#         - latest
-#         - 8
-
-# docker-sl: # Scientific Linux
-#   env: { image: "sl:${{ matrix.version }}" }
-#   needs: bootstrap
-#   runs-on: ubuntu-latest
-#   steps: *docker-steps
-#   strategy:
-#     fail-fast: false
-#     matrix:
-#       platform:
-#         - amd64
-#       version:
-#         - latest
-#         - 7
-#         - 6
-
-# docker-clefos: # For IBM Z
-#   env: { image: "clefos:${{ matrix.version }}" }
-#   needs: bootstrap
-#   runs-on: ubuntu-latest
-#   steps: *docker-steps
-#   strategy:
-#     fail-fast: false
-#     matrix:
-#       platform:
-#         - s390x
-#       version:
-#         - latest
-#         - 7
-
-# docker-almalinux:
-#   env: { image: "almalinux:${{ matrix.version }}" }
-#   needs: bootstrap
-#   runs-on: ubuntu-latest
-#   steps: *docker-steps
-#   strategy:
-#     fail-fast: false
-#     matrix:
-#       platform:
-#         - amd64
-#         - arm64/v8
-#       version:
-#         - latest
-#         - minimal # no c compiler
-#         - 8
-#         - 8-minimal # no c compiler
+          - minimal # no c compiler
+          - 8
+          - 8-minimal # no c compiler
 
 # docker-alt:
 #   env: { image: "alt:${{ matrix.version }}" }
