Fix and test Clear Linux and Mageia

diff --git a/.github/workflows/docker-official.yaml b/.github/workflows/docker-official.yaml
--- a/.github/workflows/docker-official.yaml
+++ b/.github/workflows/docker-official.yaml
@@ -60,9 +60,14 @@ jobs:
       - if: ${{ env.cont != 0 }}
         run: echo "workdir=$workdir"
       - if: ${{ env.cont != 0 }}
-        run: docker exec --user=root "$cont" mkdir "$workdir" # don't use --mode since it is not compatible
+        run: |
+          # don't use --mode since it is not compatible
+          docker exec "$cont" mkdir "$workdir" || \
+            docker exec --user=root "$cont" mkdir "$workdir"
       - if: ${{ env.cont != 0 }}
-        run: docker exec --user=root "$cont" chmod 0777 "$workdir"
+        run: |
+          docker exec "$cont" chmod 0777 "$workdir" || \
+            docker exec --user=root "$cont" chmod 0777 "$workdir"
       # Copy the artifact to the working directory
       - if: ${{ env.cont != 0 }}
         uses: actions/download-artifact@v2
@@ -169,10 +174,10 @@ jobs:
   #         - 7
   #       include:
   #         - { version: 7, platform: 386 }
-  #         ## - { version: 7, platform: arm/v7 } # yum segfaults (!?)
-  #         ## - { version: 6, platform: 386 } # error updating yum
-  #         ## - { version: 6, platform: amd64 } # error updating yum
-  #         ## - { version: 5, platform: amd64 } # error updating yum
+  #         ## - { version: 7, platform: arm/v7 } # update fails, yum segfaults (!?)
+  #         ## - { version: 6, platform: 386 } # update fails
+  #         ## - { version: 6, platform: amd64 } # update fails
+  #         ## - { version: 5, platform: amd64 } # update fails
 
   # docker-debian:
   #   env: { image: "debian:${{ matrix.version }}-slim" }
@@ -250,10 +255,10 @@ jobs:
   #       exclude:
   #         - { version: 31, platform: arm/v7 }
   #         - { version: 30, platform: arm/v7 }
-  #         - { version: 29, platform: arm/v7 } # error updating yum
-  #         - { version: 28, platform: arm/v7 } # error updating yum
-  #         - { version: 27, platform: arm/v7 } # error updating yum
-  #         - { version: 26, platform: arm/v7 } # error updating yum
+  #         - { version: 29, platform: arm/v7 } # update fails
+  #         - { version: 28, platform: arm/v7 } # update fails
+  #         - { version: 27, platform: arm/v7 } # update fails
+  #         - { version: 26, platform: arm/v7 } # update fails
   #         - { version: 27, platform: s390x }
   #         - { version: 26, platform: s390x }
 
@@ -290,7 +295,7 @@ jobs:
   #         - 8
   #         - 7
   #         - 6
-  #         ## - 5 # update repo fails
+  #         ## - 5 # update fails
   #       exclude:
   #         - { version: 6, platform: arm64/v8 }
   #         - { version: 5, platform: arm64/v8 }
@@ -319,8 +324,29 @@ jobs:
   #       include:
   #         - { version: noetic, platform: arm/v7 }
   #         - { version: melodic, platform: arm/v7 }
-  docker-photon: # VmWare Photon
-    env: {image: "photon:${{ matrix.version }}"}
+
+  # docker-photon: # VmWare Photon
+  #   env: { image: "photon:${{ matrix.version }}" }
+  #   needs: bootstrap
+  #   runs-on: ubuntu-latest
+  #   steps: *docker-steps
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       platform:
+  #         - amd64
+  #         - arm64/v8
+  #       version:
+  #         - latest
+  #         - '4.0'
+  #         - '3.0'
+  #         - '2.0'
+  #         - '1.0'
+  #       exclude:
+  #         - { version: '2.0', platform: arm64/v8 }
+  #         - { version: '1.0', platform: arm64/v8 }
+  docker-clearlinux:
+    env: {image: "clearlinux:${{ matrix.version }}"}
     needs: bootstrap
     runs-on: ubuntu-latest
     steps:
@@ -351,9 +377,14 @@ jobs:
       - if: ${{ env.cont != 0 }}
         run: echo "workdir=$workdir"
       - if: ${{ env.cont != 0 }}
-        run: docker exec --user=root "$cont" mkdir "$workdir" # don't use --mode since it is not compatible
+        run: |
+          # don't use --mode since it is not compatible
+          docker exec "$cont" mkdir "$workdir" || \
+            docker exec --user=root "$cont" mkdir "$workdir"
       - if: ${{ env.cont != 0 }}
-        run: docker exec --user=root "$cont" chmod 0777 "$workdir"
+        run: |
+          docker exec "$cont" chmod 0777 "$workdir" || \
+            docker exec --user=root "$cont" chmod 0777 "$workdir"
       # Copy the artifact to the working directory
       - if: ${{ env.cont != 0 }}
         uses: actions/download-artifact@v2
@@ -386,61 +417,99 @@ jobs:
       matrix:
         platform:
           - amd64
+        version:
+          - latest
+  docker-mageia:
+    env: {image: "mageia:${{ matrix.version }}"}
+    needs: bootstrap
+    runs-on: ubuntu-latest
+    steps:
+      # Setup multi-platform support for docker
+      - uses: docker/setup-qemu-action@v1.2.0
+      # Try to create a container for the given platform and image
+      - name: Create container
+        shell: bash
+        run: |
+          set +e
+          cont=$(docker run --pull=missing --init --detach --platform linux/${{ matrix.platform }} ${{ env.image }} tail -f /dev/null)
+          set -e
+
+          echo "cont=$cont" >> $GITHUB_ENV
+          echo "cont=$cont"
+
+          if test "x$cont" = "x"; then
+            echo "::error ::Container launch failed (${{ matrix.platform }}, ${{ env.image }})."
+            exit 1
+          fi
+      # Check platforms
+      - run: uname -a
+      - if: ${{ env.cont != 0 }}
+        run: docker exec "$cont" uname -a
+      # Create the working directory
+      - if: ${{ env.cont != 0 }}
+        run: echo "workdir=/workdir" >> $GITHUB_ENV
+      - if: ${{ env.cont != 0 }}
+        run: echo "workdir=$workdir"
+      - if: ${{ env.cont != 0 }}
+        run: |
+          # don't use --mode since it is not compatible
+          docker exec "$cont" mkdir "$workdir" || \
+            docker exec --user=root "$cont" mkdir "$workdir"
+      - if: ${{ env.cont != 0 }}
+        run: |
+          docker exec "$cont" chmod 0777 "$workdir" || \
+            docker exec --user=root "$cont" chmod 0777 "$workdir"
+      # Copy the artifact to the working directory
+      - if: ${{ env.cont != 0 }}
+        uses: actions/download-artifact@v2
+        with: {name: bootstrap-output}
+      - if: ${{ env.cont != 0 }}
+        run: docker cp - <fileinfo.tar "$cont":"$workdir"
+      # Install dependencies
+      - if: ${{ env.cont != 0 }}
+        run: docker exec --workdir="$workdir" "$cont" bin/install-deps
+      # Build
+      - if: ${{ env.cont != 0 }}
+        run: docker exec --workdir="$workdir" "$cont" ./configure
+      - if: ${{ env.cont != 0 }}
+        run: docker exec --workdir="$workdir" "$cont" cat src/config.h
+      - if: ${{ env.cont != 0 }}
+        run: docker exec --workdir="$workdir" "$cont" cat src/headers.h
+      - if: ${{ env.cont != 0 }}
+        run: docker exec --workdir="$workdir" "$cont" cat src/fileinfo/static.h
+      - if: ${{ env.cont != 0 }}
+        run: docker exec --workdir="$workdir" "$cont" make
+      - if: ${{ env.cont != 0 }}
+        run: docker exec --workdir="$workdir" "$cont" make check
+      # Cleanup
+      - if: ${{ env.cont != 0 }}
+        run: docker stop "$cont"
+      - if: ${{ env.cont != 0 }}
+        run: docker rm --force --volumes "$cont"
+    strategy:
+      fail-fast: false
+      matrix:
+        platform:
+          - amd64
+          - arm/v7
           - arm64/v8
         version:
           - latest
-          - '4.0'
-          - '3.0'
-          - '2.0'
-          - '1.0'
+          - cauldron
+          - 8
+          - 7
+          ## - 6 # update fails
+          ## - 5 # update fails
+          ## - 4 # update fails
+          ## - 3 # update fails
         exclude:
-          - {version: '2.0', platform: arm64/v8}
-          - {version: '1.0', platform: arm64/v8}
-
-# ##TODO: test
-# docker-clearlinux:
-#   env: { image: "clearlinux:${{ matrix.version }}" }
-#   needs: bootstrap
-#   runs-on: ubuntu-latest
-#   steps: *docker-steps
-#   strategy:
-#     fail-fast: false
-#     matrix:
-#       platform:
-#         - amd64
-#       version:
-#         - latest # slow install
-
-# ## TODO: test
-# docker-mageia:
-#   env: { image: "mageia:${{ matrix.version }}" }
-#   needs: bootstrap
-#   runs-on: ubuntu-latest
-#   steps: *docker-steps
-#   strategy:
-#     fail-fast: false
-#     matrix:
-#       platform:
-#         - amd64
-#         - arm/v7
-#         - arm64/v8
-#       version:
-#         - latest # slow install
-#         - cauldron # slow install
-#         - 8 # slow install
-#         - 7 # slow install
-#         - 6 # slow install
-#         - 5 # slow install
-#         - 4 # slow install
-#         - 3 # slow install
-#       exclude:
-#         - { version: 6, platform: arm64/v8 }
-#         - { version: 5, platform: arm/v7 }
-#         - { version: 5, platform: arm64/v8 }
-#         - { version: 4, platform: arm/v7 }
-#         - { version: 4, platform: arm64/v8 }
-#         - { version: 3, platform: arm/v7 }
-#         - { version: 3, platform: arm64/v8 }
+          - {version: 6, platform: arm64/v8}
+          - {version: 5, platform: arm/v7}
+          - {version: 5, platform: arm64/v8}
+          - {version: 4, platform: arm/v7}
+          - {version: 4, platform: arm64/v8}
+          - {version: 3, platform: arm/v7}
+          - {version: 3, platform: arm64/v8}
 
 # docker-rockylinux:
 #   env: { image: "rockylinux:${{ matrix.version }}" }
@@ -470,7 +539,7 @@ jobs:
 #       version:
 #         - latest
 #         - 7
-#         ## - 6 # error updating yum
+#         ## - 6 # update fails
 
 # docker-clefos: # For IBM Z
 #   env: { image: "clefos:${{ matrix.version }}" }
