Test using action-tmate for debugging

diff --git a/.github/workflows/docker.yaml b/.github/workflows/docker.yaml
--- a/.github/workflows/docker.yaml
+++ b/.github/workflows/docker.yaml
@@ -260,13 +260,86 @@ jobs:
           - version: '14.04'
             platform: s390x
             #         # 386? amd64 arm/v7? arm64/v8 ppc64le
-            #         - centos:latest # works
-            #         - centos:8 # works
-            #         # - centos:7 # no c compiler
-            #         # - centos:6.10 # yum error
-            #         # - centos:6 # yum error
-  docker-debian:
+  docker-centos:
     env: {image: "debian:${{ matrix.version }}"}
+    needs: bootstrap
+    runs-on: ubuntu-latest
+    steps:
+      # Setup multi-platform support for docker
+      - uses: docker/setup-qemu-action@v1.2.0
+      # Try to create a container for the given platform and image
+      - name: Create container
+        shell: bash
+        run: |
+          set +e
+          cont=$(docker run --pull=missing --init --detach --platform linux/${{ matrix.platform }} ${{ env.image }} tail -f /dev/null)
+          set -e
+
+          echo "cont=$cont" >> $GITHUB_ENV
+          echo "cont=$cont"
+
+          if test "x$cont" = "x"; then
+            echo "::error ::Container launch failed (${{ matrix.platform }}, ${{ env.image }})."
+            exit 1
+          fi
+      # Check platforms
+      - run: uname -a
+      - if: ${{ env.cont != 0 }}
+        run: docker exec "$cont" uname -a
+      # # Create the working directory
+      # - if: ${{ env.cont != 0 }}
+      #   run: echo "workdir=/workdir" >> $GITHUB_ENV
+      # - if: ${{ env.cont != 0 }}
+      #   run: echo "workdir=$workdir"
+      # - if: ${{ env.cont != 0 }}
+      #   run: docker exec --user=root "$cont" mkdir --mode=0777 "$workdir"
+
+      # # Copy the artifact to the working directory
+      # - if: ${{ env.cont != 0 }}
+      #   uses: actions/download-artifact@v2
+      #   with: { name: bootstrap-output }
+      # - if: ${{ env.cont != 0 }}
+      #   run: docker cp - <fileinfo.tar "$cont":"$workdir"
+
+      # # Install dependencies
+      # - if: ${{ env.cont != 0 }}
+      #   run: docker exec --workdir="$workdir" "$cont" bin/install-deps
+
+      # # Build
+      # - if: ${{ env.cont != 0 }}
+      #   run: docker exec --workdir="$workdir" "$cont" ./configure
+      # - if: ${{ env.cont != 0 }}
+      #   run: docker exec --workdir="$workdir" "$cont" cat src/config.h
+      # - if: ${{ env.cont != 0 }}
+      #   run: docker exec --workdir="$workdir" "$cont" cat src/fileinfo/static.h
+      # - if: ${{ env.cont != 0 }}
+      #   run: docker exec --workdir="$workdir" "$cont" make
+      # - if: ${{ env.cont != 0 }}
+      #   run: docker exec --workdir="$workdir" "$cont" make check
+
+      # Cleanup
+      - if: ${{ env.cont != 0 }}
+        run: docker stop "$cont"
+      - if: ${{ env.cont != 0 }}
+        run: docker rm --force --volumes "$cont"
+    strategy:
+      fail-fast: false
+      matrix:
+        platform:
+        version:
+        include:
+          - {version: 8, platform: amd64}
+          - {version: 8, platform: arm64/v8}
+          - {version: 8, platform: ppc64le,}
+          # - { version: 7, platform: 386 }
+          # - { version: 7, platform: amd64 }
+          # - { version: 7, platform: arm/v7 }
+          # - { version: 7, platform: arm64/v8 }
+          # - { version: 7, platform: ppc64le }
+          # - { version: 6, platform: 386 }
+          # - { version: 6, platform: amd64 }
+  docker-debian:
+    env: {image: "debian:${{ matrix.version }}-slim"}
     needs: bootstrap
     runs-on: ubuntu-latest
     steps:
@@ -571,18 +644,87 @@ jobs:
         platform:
           - amd64
           - arm64/v8
-          #         # amd64 arm64/v8 arm/v7?
-          #         ## Robot operating system
-          #         - ros:latest # works
-          #         #### Rolling release
-          #         - ros:rolling # works
-          #         #### ROS 2
-          #         - ros:galactic # works
-          #         - ros:foxy # works
-          #         #### ROS 1
-          #         - ros:noetic # works
-          #         - ros:melodic # works
+  docker-ros: # Robot operating system
+    env: {image: "ros:${{ matrix.version }}"}
+    needs: bootstrap
+    runs-on: ubuntu-latest
+    steps:
+      # Setup multi-platform support for docker
+      - uses: docker/setup-qemu-action@v1.2.0
+      # Try to create a container for the given platform and image
+      - name: Create container
+        shell: bash
+        run: |
+          set +e
+          cont=$(docker run --pull=missing --init --detach --platform linux/${{ matrix.platform }} ${{ env.image }} tail -f /dev/null)
+          set -e
 
+          echo "cont=$cont" >> $GITHUB_ENV
+          echo "cont=$cont"
+
+          if test "x$cont" = "x"; then
+            echo "::error ::Container launch failed (${{ matrix.platform }}, ${{ env.image }})."
+            exit 1
+          fi
+      # Check platforms
+      - run: uname -a
+      - if: ${{ env.cont != 0 }}
+        run: docker exec "$cont" uname -a
+      # # Create the working directory
+      # - if: ${{ env.cont != 0 }}
+      #   run: echo "workdir=/workdir" >> $GITHUB_ENV
+      # - if: ${{ env.cont != 0 }}
+      #   run: echo "workdir=$workdir"
+      # - if: ${{ env.cont != 0 }}
+      #   run: docker exec --user=root "$cont" mkdir --mode=0777 "$workdir"
+
+      # # Copy the artifact to the working directory
+      # - if: ${{ env.cont != 0 }}
+      #   uses: actions/download-artifact@v2
+      #   with: { name: bootstrap-output }
+      # - if: ${{ env.cont != 0 }}
+      #   run: docker cp - <fileinfo.tar "$cont":"$workdir"
+
+      # # Install dependencies
+      # - if: ${{ env.cont != 0 }}
+      #   run: docker exec --workdir="$workdir" "$cont" bin/install-deps
+
+      # # Build
+      # - if: ${{ env.cont != 0 }}
+      #   run: docker exec --workdir="$workdir" "$cont" ./configure
+      # - if: ${{ env.cont != 0 }}
+      #   run: docker exec --workdir="$workdir" "$cont" cat src/config.h
+      # - if: ${{ env.cont != 0 }}
+      #   run: docker exec --workdir="$workdir" "$cont" cat src/fileinfo/static.h
+      # - if: ${{ env.cont != 0 }}
+      #   run: docker exec --workdir="$workdir" "$cont" make
+      # - if: ${{ env.cont != 0 }}
+      #   run: docker exec --workdir="$workdir" "$cont" make check
+
+      # Cleanup
+      - if: ${{ env.cont != 0 }}
+        run: docker stop "$cont"
+      - if: ${{ env.cont != 0 }}
+        run: docker rm --force --volumes "$cont"
+    strategy:
+      fail-fast: false
+      matrix:
+        platform:
+          - amd64
+          - arm64/v8
+        version:
+          - latest
+          #### Rolling release
+          - rolling
+          #### ROS 2
+          - galactic
+          - foxy
+          #### ROS 1
+          - noetic
+          - melodic
+        include:
+          - {platform: arm/v7, version: noetic}
+          - {platform: arm/v7, version: melodic,}
           ## VmWare Photon
           # - photon:latest # needs coreutils but is also missing `as`
 
