Test some of the smaller distros

diff --git a/.github/workflows/docker-official.yaml b/.github/workflows/docker-official.yaml
--- a/.github/workflows/docker-official.yaml
+++ b/.github/workflows/docker-official.yaml
@@ -168,9 +168,9 @@ jobs:
   #       include:
   #         - { version: 7, platform: 386 }
   #         # - { version: 7, platform: arm/v7 } # yum segfaults (!?)
-  #         # - { version: 6, platform: 386 } # error finding repo
-  #         # - { version: 6, platform: amd64 } # error finding repo
-  #         # - { version: 5, platform: amd64 } # error finding repo
+  #         # - { version: 6, platform: 386 } # error updating yum
+  #         # - { version: 6, platform: amd64 } # error updating yum
+  #         # - { version: 5, platform: amd64 } # error updating yum
 
   # docker-debian:
   #   env: { image: "debian:${{ matrix.version }}-slim" }
@@ -216,8 +216,46 @@ jobs:
   #         - { version: '8.11', platform: mips64le }
   #         - { version: '8.11', platform: ppc64le }
   #         - { version: '8.11', platform: s390x }
-  docker-fedora:
-    env: {image: "fedora:${{ matrix.version }}"}
+
+  # docker-fedora:
+  #   env: { image: "fedora:${{ matrix.version }}" }
+  #   needs: bootstrap
+  #   runs-on: ubuntu-latest
+  #   steps: *docker-steps
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       platform:
+  #         - amd64
+  #         - arm/v7
+  #         - arm64/v8
+  #         - ppc64le
+  #         - s390x
+  #       version:
+  #         - latest
+  #         - rawhide
+  #         - 36
+  #         - 35
+  #         - 34
+  #         - 33
+  #         - 32
+  #         - 31
+  #         - 30
+  #         - 29
+  #         - 28
+  #         - 27
+  #         - 26
+  #       exclude:
+  #         - { version: 31, platform: arm/v7 }
+  #         - { version: 30, platform: arm/v7 }
+  #         - { version: 29, platform: arm/v7 } # error updating yum
+  #         - { version: 28, platform: arm/v7 } # error updating yum
+  #         - { version: 27, platform: arm/v7 } # error updating yum
+  #         - { version: 26, platform: arm/v7 } # error updating yum
+  #         - { version: 27, platform: s390x }
+  #         - { version: 26, platform: s390x }
+  docker-amazonlinux:
+    env: {image: "amazonlinux:${{ matrix.version }}"}
     needs: bootstrap
     runs-on: ubuntu-latest
     steps:
@@ -281,113 +319,241 @@ jobs:
       matrix:
         platform:
           - amd64
-          - arm/v7
           - arm64/v8
-          - ppc64le
-          - s390x
         version:
           - latest
-          - rawhide
-          - 36
-          - 35
-          - 34
-          - 33
-          - 32
-          - 31
-          - 30
-          - 29
-          - 28
-          - 27
-          - 26
+          - 2
+          - 1
         exclude:
-          - {version: 31, platform: arm/v7}
-          - {version: 30, platform: arm/v7}
-          - {version: 27, platform: s390x}
-          - {version: 26, platform: s390x}
+          - {version: 1, platform: arm64/v8}
+  docker-oraclelinux:
+    env: {image: "oraclelinux:${{ matrix.version }}"}
+    needs: bootstrap
+    runs-on: ubuntu-latest
+    steps:
+      # Setup multi-platform support for docker
+      - uses: docker/setup-qemu-action@v1.2.0
+      # Try to create a container for the given platform and image
+      - name: Create container
+        shell: bash
+        run: |
+          set +e
+          cont=$(docker run --pull=missing --init --detach --platform linux/${{ matrix.platform }} ${{ env.image }} tail -f /dev/null)
+          set -e
 
-# docker-amazonlinux:
-#   env: { image: "amazonlinux:${{ matrix.version }}" }
-#   needs: bootstrap
-#   runs-on: ubuntu-latest
-#   steps: *docker-steps
-#   strategy:
-#     fail-fast: false
-#     matrix:
-#       platform:
-#         - amd64
-#         - arm64/v8
-#       version:
-#         - latest
-#         - 2
-#         - 1
-#       exclude:
-#         - { version: 1, platform: arm64/v8 }
+          echo "cont=$cont" >> $GITHUB_ENV
+          echo "cont=$cont"
 
-# docker-oraclelinux:
-#   env: { image: "oraclelinux:${{ matrix.version }}" }
-#   needs: bootstrap
-#   runs-on: ubuntu-latest
-#   steps: *docker-steps
-#   strategy:
-#     fail-fast: false
-#     matrix:
-#       platform:
-#         - amd64
-#         - arm64/v8
-#       version:
-#         - 8
-#         - 7
-#         - 6
-#         - 5
-#       exclude:
-#         - { version: 6, platform: arm64/v8 }
-#         - { version: 5, platform: arm64/v8 }
+          if test "x$cont" = "x"; then
+            echo "::error ::Container launch failed (${{ matrix.platform }}, ${{ env.image }})."
+            exit 1
+          fi
+      # Check platforms
+      - run: uname -a
+      - if: ${{ env.cont != 0 }}
+        run: docker exec "$cont" uname -a
+      # Create the working directory
+      - if: ${{ env.cont != 0 }}
+        run: echo "workdir=/workdir" >> $GITHUB_ENV
+      - if: ${{ env.cont != 0 }}
+        run: echo "workdir=$workdir"
+      - if: ${{ env.cont != 0 }}
+        run: docker exec --user=root "$cont" mkdir "$workdir" # don't use --mode since it is not compatible
+      - if: ${{ env.cont != 0 }}
+        run: docker exec --user=root "$cont" chmod 0777 "$workdir"
+      # Copy the artifact to the working directory
+      - if: ${{ env.cont != 0 }}
+        uses: actions/download-artifact@v2
+        with: {name: bootstrap-output}
+      - if: ${{ env.cont != 0 }}
+        run: docker cp - <fileinfo.tar "$cont":"$workdir"
+      # Install dependencies
+      - if: ${{ env.cont != 0 }}
+        run: docker exec --workdir="$workdir" "$cont" bin/install-deps
+      # Build
+      - if: ${{ env.cont != 0 }}
+        run: docker exec --workdir="$workdir" "$cont" ./configure
+      - if: ${{ env.cont != 0 }}
+        run: docker exec --workdir="$workdir" "$cont" cat src/config.h
+      - if: ${{ env.cont != 0 }}
+        run: docker exec --workdir="$workdir" "$cont" cat src/fileinfo/static.h
+      - if: ${{ env.cont != 0 }}
+        run: docker exec --workdir="$workdir" "$cont" make
+      - if: ${{ env.cont != 0 }}
+        run: docker exec --workdir="$workdir" "$cont" make check
+        # # Cleanup
+        # - if: ${{ env.cont != 0 }}
+        #   run: docker stop "$cont"
+        # - if: ${{ env.cont != 0 }}
+        #   run: docker rm --force --volumes "$cont"
+    strategy:
+      fail-fast: false
+      matrix:
+        platform:
+          - amd64
+          - arm64/v8
+        version:
+          - 8
+          - 7
+          - 6
+          - 5
+        exclude:
+          - {version: 6, platform: arm64/v8}
+          - {version: 5, platform: arm64/v8}
+  docker-ros: # Robot operating system
+    env: {image: "ros:${{ matrix.version }}"}
+    needs: bootstrap
+    runs-on: ubuntu-latest
+    steps:
+      # Setup multi-platform support for docker
+      - uses: docker/setup-qemu-action@v1.2.0
+      # Try to create a container for the given platform and image
+      - name: Create container
+        shell: bash
+        run: |
+          set +e
+          cont=$(docker run --pull=missing --init --detach --platform linux/${{ matrix.platform }} ${{ env.image }} tail -f /dev/null)
+          set -e
 
-# docker-ros: # Robot operating system
-#   env: { image: "ros:${{ matrix.version }}" }
-#   needs: bootstrap
-#   runs-on: ubuntu-latest
-#   steps: *docker-steps
-#   strategy:
-#     fail-fast: false
-#     matrix:
-#       platform:
-#         - amd64
-#         - arm64/v8
-#       version:
-#         - latest
-#         #### Rolling release
-#         - rolling
-#         #### ROS 2
-#         - galactic
-#         - foxy
-#         #### ROS 1
-#         - noetic
-#         - melodic
-#       include:
-#         - { version: noetic, platform: arm/v7 }
-#         - { version: melodic, platform: arm/v7 }
+          echo "cont=$cont" >> $GITHUB_ENV
+          echo "cont=$cont"
 
-# docker-photon: # VmWare Photon
-#   env: { image: "photon:${{ matrix.version }}" }
-#   needs: bootstrap
-#   runs-on: ubuntu-latest
-#   steps: *docker-steps
-#   strategy:
-#     fail-fast: false
-#     matrix:
-#       platform:
-#         - amd64
-#         - arm64/v8
-#       version:
-#         - latest # needs coreutils but is also missing `as`
-#         - '4.0'
-#         - '3.0'
-#         - '2.0'
-#         - '1.0'
-#       exclude:
-#         - { version: '2.0', platform: arm64/v8 }
-#         - { version: '1.0', platform: arm64/v8 }
+          if test "x$cont" = "x"; then
+            echo "::error ::Container launch failed (${{ matrix.platform }}, ${{ env.image }})."
+            exit 1
+          fi
+      # Check platforms
+      - run: uname -a
+      - if: ${{ env.cont != 0 }}
+        run: docker exec "$cont" uname -a
+      # Create the working directory
+      - if: ${{ env.cont != 0 }}
+        run: echo "workdir=/workdir" >> $GITHUB_ENV
+      - if: ${{ env.cont != 0 }}
+        run: echo "workdir=$workdir"
+      - if: ${{ env.cont != 0 }}
+        run: docker exec --user=root "$cont" mkdir "$workdir" # don't use --mode since it is not compatible
+      - if: ${{ env.cont != 0 }}
+        run: docker exec --user=root "$cont" chmod 0777 "$workdir"
+      # Copy the artifact to the working directory
+      - if: ${{ env.cont != 0 }}
+        uses: actions/download-artifact@v2
+        with: {name: bootstrap-output}
+      - if: ${{ env.cont != 0 }}
+        run: docker cp - <fileinfo.tar "$cont":"$workdir"
+      # Install dependencies
+      - if: ${{ env.cont != 0 }}
+        run: docker exec --workdir="$workdir" "$cont" bin/install-deps
+      # Build
+      - if: ${{ env.cont != 0 }}
+        run: docker exec --workdir="$workdir" "$cont" ./configure
+      - if: ${{ env.cont != 0 }}
+        run: docker exec --workdir="$workdir" "$cont" cat src/config.h
+      - if: ${{ env.cont != 0 }}
+        run: docker exec --workdir="$workdir" "$cont" cat src/fileinfo/static.h
+      - if: ${{ env.cont != 0 }}
+        run: docker exec --workdir="$workdir" "$cont" make
+      - if: ${{ env.cont != 0 }}
+        run: docker exec --workdir="$workdir" "$cont" make check
+        # # Cleanup
+        # - if: ${{ env.cont != 0 }}
+        #   run: docker stop "$cont"
+        # - if: ${{ env.cont != 0 }}
+        #   run: docker rm --force --volumes "$cont"
+    strategy:
+      fail-fast: false
+      matrix:
+        platform:
+          - amd64
+          - arm64/v8
+        version:
+          - latest
+          #### Rolling release
+          - rolling
+          #### ROS 2
+          - galactic
+          - foxy
+          #### ROS 1
+          - noetic
+          - melodic
+        include:
+          - {version: noetic, platform: arm/v7}
+          - {version: melodic, platform: arm/v7}
+  docker-photon: # VmWare Photon
+    env: {image: "photon:${{ matrix.version }}"}
+    needs: bootstrap
+    runs-on: ubuntu-latest
+    steps:
+      # Setup multi-platform support for docker
+      - uses: docker/setup-qemu-action@v1.2.0
+      # Try to create a container for the given platform and image
+      - name: Create container
+        shell: bash
+        run: |
+          set +e
+          cont=$(docker run --pull=missing --init --detach --platform linux/${{ matrix.platform }} ${{ env.image }} tail -f /dev/null)
+          set -e
+
+          echo "cont=$cont" >> $GITHUB_ENV
+          echo "cont=$cont"
+
+          if test "x$cont" = "x"; then
+            echo "::error ::Container launch failed (${{ matrix.platform }}, ${{ env.image }})."
+            exit 1
+          fi
+      # Check platforms
+      - run: uname -a
+      - if: ${{ env.cont != 0 }}
+        run: docker exec "$cont" uname -a
+      # Create the working directory
+      - if: ${{ env.cont != 0 }}
+        run: echo "workdir=/workdir" >> $GITHUB_ENV
+      - if: ${{ env.cont != 0 }}
+        run: echo "workdir=$workdir"
+      - if: ${{ env.cont != 0 }}
+        run: docker exec --user=root "$cont" mkdir "$workdir" # don't use --mode since it is not compatible
+      - if: ${{ env.cont != 0 }}
+        run: docker exec --user=root "$cont" chmod 0777 "$workdir"
+      # Copy the artifact to the working directory
+      - if: ${{ env.cont != 0 }}
+        uses: actions/download-artifact@v2
+        with: {name: bootstrap-output}
+      - if: ${{ env.cont != 0 }}
+        run: docker cp - <fileinfo.tar "$cont":"$workdir"
+      # Install dependencies
+      - if: ${{ env.cont != 0 }}
+        run: docker exec --workdir="$workdir" "$cont" bin/install-deps
+      # Build
+      - if: ${{ env.cont != 0 }}
+        run: docker exec --workdir="$workdir" "$cont" ./configure
+      - if: ${{ env.cont != 0 }}
+        run: docker exec --workdir="$workdir" "$cont" cat src/config.h
+      - if: ${{ env.cont != 0 }}
+        run: docker exec --workdir="$workdir" "$cont" cat src/fileinfo/static.h
+      - if: ${{ env.cont != 0 }}
+        run: docker exec --workdir="$workdir" "$cont" make
+      - if: ${{ env.cont != 0 }}
+        run: docker exec --workdir="$workdir" "$cont" make check
+        # # Cleanup
+        # - if: ${{ env.cont != 0 }}
+        #   run: docker stop "$cont"
+        # - if: ${{ env.cont != 0 }}
+        #   run: docker rm --force --volumes "$cont"
+    strategy:
+      fail-fast: false
+      matrix:
+        platform:
+          - amd64
+          - arm64/v8
+        version:
+          - latest # needs coreutils but is also missing `as`
+          - '4.0'
+          - '3.0'
+          - '2.0'
+          - '1.0'
+        exclude:
+          - {version: '2.0', platform: arm64/v8}
+          - {version: '1.0', platform: arm64/v8}
 
 # docker-clearlinux:
 #   env: { image: "clearlinux:${{ matrix.version }}" }
